export const CLASS_PREFIX = 'rplayer_';

export const CLASS_PLAYER = 'rplayer';

export const EVENT = {
  ENTER_FULLSCREEN: 'ENTER_FULLSCREEN',
  EXIT_FULLSCREEN: 'EXIT_FULLSCREEN',
  WEB_ENTER_FULLSCREEN: 'WEB_ENTER_FULLSCREEN',
  WEB_EXIT_FULLSCREEN: 'WEB_EXIT_FULLSCREEN',
  DURATION_CHANGE: 'DURATION_CHANGE',
  RATE_CHANGE: 'RATE_CHANGE',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  ENDED: 'ENDED',
  WAITING: 'WAITING',
  STALLED: 'STALLED',
  CANPLAY: 'CANPLAY',
  LOADED_METADATA: 'LOADED_METADATA',
  ERROR: 'ERROR',
  SEEKED: 'SEEKED',
  TIME_UPDATE: 'TIME_UPDATE',
  VOLUME_CHANGE: 'VOLUME_CHANGE',
  PROGRESS: 'PROGRESS',
  ENTER_PIP: 'ENTER_PIP',
  EXIT_PIP: 'EXIT_PIP',
  LOADING_SHOW: 'LOADING_SHOW',
  LOADING_HIDE: 'LOADING_HIDE',
  MOUNTED: 'MOUNTED',
} as const;
