export const CLASS_PREFIX = 'rplayer_';

export const CLASS_PLAYER = 'rplayer';

export const EVENT = {
  ENTER_FULLSCREEN: 'ENTER_FULLSCREEN',
  EXIT_FULLSCREEN: 'EXIT_FULLSCREEN',
  WEB_ENTER_FULLSCREEN: 'WEB_ENTER_FULLSCREEN',
  WEB_EXIT_FULLSCREEN: 'WEB_EXIT_FULLSCREEN',
  DURATION_CHANGE: 'DURATION_CHANGE',
  RATE_CHANGE: 'RATE_CHANGE',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  ENDED: 'ENDED',
  WAITING: 'WAITING',
  STALLED: 'STALLED',
  CANPLAY: 'CANPLAY',
  LOADED_METADATA: 'LOADED_METADATA',
  ERROR: 'ERROR',
  SEEKED: 'SEEKED',
  TIME_UPDATE: 'TIME_UPDATE',
  VOLUME_CHANGE: 'VOLUME_CHANGE',
  PROGRESS: 'PROGRESS',
} as const;

// BEFORE_MOUNT = 'BeforeMount',
// MOUNTED = 'Mounted',
// CONTROLS_SHOW = 'ControlsShow',
// CONTROLS_HIDE = 'ControlsHide',

// DURATION_CHANGE = 'DurationChange',
// TIME_UPDATE = 'TimeUpdate',
// VOLUME_CHANGE = 'VolumeChange',
// LOADED_METADATA = 'LoadedMetadata',
// RATE_CHANGE = 'RateChange',
// PLAY = 'Play',
// PAUSE = 'Pause',
// ENDED = 'Ended',
// PROGRESS = 'Progress',
// CANPLAY = 'Canplay',
// WAITING = 'Waiting',
// PLAYING = 'Playing',
// STALLED = 'Stalled',
// ERROR = 'Error',
// SEEKED = 'Seeked',
// BREAK_POINT_CHANGE = 'BreakPointChange',
// CLICK_CONTROL_MASK = 'ClickControlMask',
// CLICK_OUTSIDE = 'ClickOutside',
// PLAYER_CLICK = 'PlayerClick',
// PLAYER_CONTEXT_MENU = 'PlayerContextMenu',
// PLAYER_DBLCLICK = 'PlayerDblclick',
// PLAYER_MOUSE_MOVE = 'PlayerMouseMove',
// PLAYER_MOUSE_LEAVE = 'PlayerMouseLeave',
// PLAYER_RESIZE = 'PlayerResize',
// SETTING_SELECTED = 'SettingSelected',
// LOADING_SHOW = 'LoadingShow',
// LOADING_HIDE = 'LoadingHide',
